trigger: none

pool:
  name: todo-infra-agent-pool

steps:

# Step 1: Install Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

# Step 2: Terraform Init (with backend using federated credential)
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Todo-infra-setup'
    backendServiceArm: 'SP-1-Federated-Cred'
    backendAzureRmResourceGroupName: 'test-rg'
    backendAzureRmStorageAccountName: 'teststs20234'
    backendAzureRmContainerName: 'statefile-container1'
    backendAzureRmKey: 'terraform.tfstate'
    environmentServiceNameAzureRM: 'SP-1-Federated-Cred'

# Step 3: Terraform Format
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'custom'
    customCommand: 'fmt'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Todo-infra-setup'
    outputTo: 'console'
    environmentServiceNameAzureRM: 'SP-1-Federated-Cred'

# Step 4: Terraform Validate
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Todo-infra-setup'
    environmentServiceNameAzureRM: 'SP-1-Federated-Cred'

# Step 5: Terraform Plan
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Todo-infra-setup'
    environmentServiceNameAzureRM: 'SP-1-Federated-Cred'

# Step 6: Terraform Apply
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Todo-infra-setup'
    environmentServiceNameAzureRM: 'SP-1-Federated-Cred'
