trigger:
  branches:
    include:
      - main

pool:
  name: todo-infra-agent-pool

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.14.2'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '"C:\\todo-infra-agent1\\Todo-infra-setup"'
    backendServiceArm: 'SP-1-Federated-Cred'
    backendAzureRmResourceGroupName: 'test-rg'
    backendAzureRmStorageAccountName: 'teststs20234'
    backendAzureRmContainerName: 'statefile-container1'
    backendAzureRmKey: 'terraform.tfstate'
    useAzureADAuthentication: true

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '"C:\\todo-infra-agent1\\Todo-infra-setup"'
    environmentServiceNameAzureRM: 'SP-1-Federated-Cred'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '"C:\\todo-infra-agent1\\Todo-infra-setup"'
    environmentServiceNameAzureRM: 'SP-1-Federated-Cred'
    args: '-auto-approve'
