trigger: none

pool:
  name: todo-infra-agent-pool

steps:
# Install Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

# Terraform Init (Backend)
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Todo-infra-setup'
    backendServiceArm: 'sp-2'
    backendAzureRmResourceGroupName: 'test-rg'
    backendAzureRmStorageAccountName: 'teststs20234'
    backendAzureRmContainerName: 'statefile-container1'
    backendAzureRmKey: 'terraform.tfstate'

# Terraform fmt
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Todo-infra-setup'
    customCommand: 'fmt'

# Terraform validate
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Todo-infra-setup'

# Terraform plan
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Todo-infra-setup'
    environmentServiceNameAzureRM: 'sp-2'

# Terraform apply
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Todo-infra-setup'
    environmentServiceNameAzureRM: 'sp-2'
    commandOptions: '-auto-approve'
